name: SlabSit
api: 3.14.0
main: korado531m7\SlabSit\SlabSit
version: 1.5.8
author: korado531m7
description: Enable to sit on the slab block
mcpe-protocol: [407, 408, 419]
permissions:
  slabsit.toggle:
    description: "Toggle to sit"
    default: true
